# Generated by Django 4.2.28 on 2026-02-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Briefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("author", models.CharField(max_length=50, verbose_name="작성자")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="briefing/",
                        verbose_name="대표이미지",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="작성일")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="조회수")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
