# Generated by Django 5.2.11 on 2026-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_event_attachment_eventattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='events/images/'),
        ),
    ]
