# Generated by Django 5.2.11 on 2026-03-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Briefing',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', '주요행사'), ('briefing', '성과브리핑')], default='event', max_length=20),
        ),
    ]
