# Generated by Django 5.2.11 on 2026-03-06 08:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
